require("dotenv").config();
const express = require("express");
const cors=require('cors');
const app = express();
const mongoose = require("mongoose");
mongoose.connect(process.env.DATABASE_URL, { useNewUrlParser: true }); 
const db = mongoose.connection;
db.on("error", error => console.log(error));
db.once("open", () => console.log("connection to db established"));
app.use(express.json());
const usersRouter = require("./routes/weeks");
app.use("/weeks", usersRouter);
app.use(cors());
app.listen(process.env.PORT, () => console.log(`server has started at port ${process.env.PORT}`));
